version: '3.4'
services:
  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - /home/local/FARFETCH/isaac.reis/cassandra_data:/var/lib/cassandra
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: /home/local/FARFETCH/isaac.reis/mongo_data/
        target: /data/db
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    links:
      - zookeeper
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /home/local/FARFETCH/isaac.reis/elastic_data:/var/lib/elastic
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - elastic
      
networks:
  elastic:
    driver: bridge